seed:
  name: adv_bench
  num_samples: 3

attack:
  type: crescendo
  max_turns: 7
  max_backtracks: 2
  scoring_threshold: 0.8
  adversarial:
    api_type: together
    model_name: meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo
    temperature: 1.2
    top_p: 0.9
    max_completion_tokens: 1024
  scoring:
    api_type: together
    model_name: meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo
    temperature: 0.7
    top_p: 0.9
    max_completion_tokens: 1024
  objective:
    api_type: together
    model_name: meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo
    temperature: 0.2
    top_p: 0.9
    max_completion_tokens: 1024